// <auto-generated />
using System;
using FunFoodServer.Repositories.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FunFoodServer.Repositories.Migrations
{
    [DbContext(typeof(FunFoodDbContext))]
    partial class FunFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("FunFood")
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FunFoodServer.Domain.Model.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(40);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(80);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasName("Index_Email");

                    b.ToTable("USER");
                });

            modelBuilder.Entity("FunFoodServer.Domain.Model.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthday")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(new DateTime(2018, 9, 26, 0, 0, 0, 0, DateTimeKind.Local));

                    b.Property<string>("Facebook")
                        .HasMaxLength(50);

                    b.Property<string>("FirstName")
                        .HasMaxLength(20);

                    b.Property<int>("Gender")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasDefaultValue(0);

                    b.Property<string>("GooglePlus")
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .HasMaxLength(20);

                    b.Property<string>("Location")
                        .HasMaxLength(30);

                    b.Property<string>("Twitter")
                        .HasMaxLength(50);

                    b.Property<Guid>("UserId");

                    b.Property<string>("Youtube")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("USER_PROFILE");
                });

            modelBuilder.Entity("FunFoodServer.Domain.Model.UserProfile", b =>
                {
                    b.HasOne("FunFoodServer.Domain.Model.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FunFoodServer.Domain.Model.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
